export const CREATE_PERSONA = "CREATE_PERSONA";

export const CREATE_PERSONA_EP = "CREATE_PERSONA_EP";

export const CREATE_DIRECCION = "CREATE_DIRECCION";

export const RETRIEVE_LOCALIDADES = "RETRIEVE_LOCALIDADES";

export const RETRIEVE_MUNICIPIOS = "RETRIEVE_MUNICIPIOS";