export const CREATE_PERSONA = "CREATE_PERSONA";

export const CREATE_PERSONA_EP = "CREATE_PERSONA_EP";

export const CREATE_DIRECCION = "CREATE_DIRECCION";

export const RETRIEVE_LOCALIDADES = "RETRIEVE_LOCALIDADES";

export const RETRIEVE_MUNICIPIOS = "RETRIEVE_MUNICIPIOS";

export const RETRIEVE_ENFERMEDADES = "RETRIEVE_ENFERMEDADES";

export const RETRIEVE_DIAGNOSTICOS_EP = "RETRIEVE_DIAGNOSTICOS_EP";

export const CREATE_DIAGNOSTICO = "CREATE_DIAGNOSTICO";

export const UPDATE_DIAGNOSTICO = "UPDATE_DIAGNOSTICO";

export const DELETE_DIAGNOSTICO = "DELETE_DIAGNOSTICO"

export const RETRIEVE_EVOLUCION_EP = "RETRIEVE_EVOLUCION_EP";

export const CREATE_EVOLUCION = "CREATE_EVOLUCION";

export const UPDATE_EVOLUCION = "UPDATE_EVOLUCION";

export const DELETE_EVOLUCION = "DELETE_EVOLUCION"